apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-service
  template:
    metadata:
      name: chat-service
      labels:
        app: chat-service
    spec:
      containers:
      - name: chat-service
        image: modulera/chat-service
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 5200
          initialDelaySeconds: 30
          periodSeconds: 2
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "1"
            memory: "1Gi"
        envFrom:
          - secretRef:
              name: chat-service-secret