apiVersion: v1
kind: Service
metadata:
  name: chat-service-service
spec:
  selector:
    app: chat-service
  ports:
  - name: http
    port: 80
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer